#ifndef SMPC_IO_H
#define SMPC_IO_H
#include <stdio.h>
#include "smpc.h"

#define SMPC_IO_ERROR_FILENOTFOUND -1
#define SMPC_IO_ERROR_PARSE_GATES_EXPECTED -2
#define SMPC_IO_ERROR_PARSE_GATES_INVALID_LENGTH -3
#define SMPC_IO_ERROR_PARSE_GATES_INVALID_INDEX -4
#define SMPC_IO_ERROR_PARSE_GATES_INDEX_ORDER -5
#define SMPC_IO_ERROR_PARSE_GATES_EXPECTED_GATE -6
#define SMPC_IO_ERROR_PARSE_GATES_INVALID_TYPE -7
#define SMPC_IO_ERROR_PARSE_INPUT_EXPECTED_WIRES -8
#define SMPC_IO_ERROR_PARSE_INPUT_INVALID_INDEX -9
#define SMPC_IO_ERROR_PARSE_INPUT_INDEX_ORDER -10
#define SMPC_IO_ERROR_PARSE_INPUT_OBRACKET_EXPECTED -11
#define SMPC_IO_ERROR_PARSE_INPUT_INVALID_GATE -12
#define SMPC_IO_ERROR_PARSE_INPUT_INVALID_CHAR -13
#define SMPC_IO_ERROR_PARSE_INPUT_CBRACKET_EXPECTED -14
#define SMPC_IO_ERROR_PARSE_INPUT_GATE_OUT_OF_RANGE -15
#define SMPC_IO_ERROR_PARSE_INPUT_EXPECTED -16
#define SMPC_IO_ERROR_PARSE_INPUT_TOO_MANY_GATE_INPUT_LINES -17
#define SMPC_IO_ERROR_PARSE_WIRES_EXPECTED_OUTPUT -18
#define SMPC_IO_ERROR_PARSE_WIRES_LPARENS_EXPECTED -19
#define SMPC_IO_ERROR_PARSE_WIRES_COMMA_EXPECTED -20
#define SMPC_IO_ERROR_PARSE_WIRES_PARAM1_INVALID -21
#define SMPC_IO_ERROR_PARSE_WIRES_PARAM2_INVALID -22
#define SMPC_IO_ERROR_PARSE_WIRES_PARAM1_OUT_OF_RANGE -23
#define SMPC_IO_ERROR_PARSE_WIRES_PARAM2_OUT_OF_RANGE -24
#define SMPC_IO_ERROR_PARSE_WIRES_RPARENS_EXPECTED -25
#define SMPC_IO_ERROR_PARSE_WIRES_TOO_MANY_GATE_INPUT_LINES -26
#define SMPC_IO_ERROR_PARSE_OUTPUT_INVALID_NUMBER -27
#define SMPC_IO_ERROR_PARSE_OUTPUT_OUT_OF_RANGE -28
#define SMPC_IO_ERROR_PARSE_INVALID_GRAPH_POINTER -29

int smpc_io_parse_graph_from_file(smpc_graph** graph, char* filename);
void smpc_io_print_graph(smpc_graph* graph, FILE* f);

#endif
